version: "3.8"
services:
  api:
    container_name: shogi_server_api
    build:
      context: ./api
    ports:
      - 3000:3000
    networks:
      - shogi_server_network
  server:
    container_name: shogi_server_nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - 80:80
    networks:
      - shogi_server_network
    depends_on:
      - api
networks: 
  shogi_server_network:
    external: false
